language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install -U six jupyter notebook ipython<6.0;
    else
      pip install -U jupyter notebook ipython>=6.0;
    fi
script: nosetests
