language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      pip install six jupyter notebook 'ipython>=5.0,<6.0';
    else
      pip install jupyter notebook 'ipython>=6.0';
    fi
script: nosetests
